language: php

php:
    - 5.4
    - 5.5

before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --prefer-source --dev

script:
    - vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests/
    - vendor/bin/phpcs --standard=PSR2 -n src/ tests/

